name = "raft"
description = "Raft consensus in Ada with a deterministic multi-node test harness"
version = "0.1.0-dev"

authors = ["Patrice Freydiere"]
maintainers = ["Patrice Freydiere <frett27@gmail.com>"]
maintainers-logins = ["frett27"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

# executables = ["testcommunication"]



[[depends-on]]
gnatprove = "^14.1.1"
