/* Configuration for raft generated by Alire */
#ifndef RAFT_CONFIG_H
#define RAFT_CONFIG_H
#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "raft"
#define ALIRE_HOST_OS "linux"
#define ALIRE_HOST_ARCH "x86_64"
#define ALIRE_HOST_DISTRO "ubuntu"
#define BUILD_PROFILE development
#endif
